language: python
python:
  - 2.6
  - 2.7
  - 3.3
before_install:
  - sudo apt-get install python-dev
install:
  - pip install --use-mirrors pytest-cov numpy
  - python setup.py install
script: "cd test; py.test --cov-report term-missing --cov ln"
